/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "Stm32F407_Regs.h"
#include "Std_Types.h"

void initIO(void);

int main(void)
{
	initIO();
    /* Loop forever */
	while(1)
	{
		spGPIOD_ODR->pin_12 = Pin_High;
		spGPIOD_ODR->pin_13 = Pin_Low;
		spGPIOD_ODR->pin_14 = Pin_High;
		spGPIOD_ODR->pin_15 = Pin_Low;
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		spGPIOD_ODR->pin_12 = Pin_Low;
		spGPIOD_ODR->pin_13 = Pin_High;
		spGPIOD_ODR->pin_14 = Pin_Low;
		spGPIOD_ODR->pin_15 = Pin_High;
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
		for(uint32 i=0 ; i < 300000 ; i++ );
	}

}

void initIO(void)
{
spRCC_AHB1ENR->gpiod_en = 1u;

spGPIOD_MODER->pin_12 = General_Purpose_output_mode;
spGPIOD_MODER->pin_13 = General_Purpose_output_mode;
spGPIOD_MODER->pin_14 = General_Purpose_output_mode;
spGPIOD_MODER->pin_15 = General_Purpose_output_mode;
spGPIOD_OTYPER->pin_12 = Output_push_pull;
spGPIOD_OTYPER->pin_13 = Output_push_pull;
spGPIOD_OTYPER->pin_14 = Output_push_pull;
spGPIOD_OTYPER->pin_15 = Output_push_pull;
spGPIOD_PUPDR->pin_12 = Pull_down;
spGPIOD_PUPDR->pin_13 = Pull_down;
spGPIOD_PUPDR->pin_14 = Pull_down;
spGPIOD_PUPDR->pin_15 = Pull_down;
}
